version: "3.9"
services:
  backend:
    build: ./backend
    container_name: unified-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./models:/models
    networks:
      - unified_net

  frontend:
    build: ./frontend-ui
    container_name: unified-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - unified_net

  n8n:
    image: n8nio/n8n:latest
    container_name: unified-n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - unified_net

  prometheus:
    image: prom/prometheus:latest
    container_name: unified-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - unified_net

  grafana:
    image: grafana/grafana:latest
    container_name: unified-grafana
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - unified_net

networks:
  unified_net:
    driver: bridge
